# docker-compose.yml
redis:
  image: redis:alpine
  container_name: redis
  command: ['redis-server', '--appendonly', 'yes']
  environment:
    - REDIS_REPLICATION_MODE=master
  ports:
    - '6379:6379'
  volumes:
    - redis-data:/data
app:
  build: ./
  volumes:
    - ./:/app
  links:
    - redis
    - mongodb
  ports:
    - 5000:5000
  environment:
    - REDIS_URL=redis://redis
    - NODE_ENV=development
    - PORT=5000
    - DB_CONNECTION_STRING=mongodb://mongodb:27017/labs
  command:
    ['npm', 'start']
mongodb:
  image: mongo
  container_name: mongo
  ports:
    - '27017:27017'
  volumes:
    - mongo-data:/data